version: '3.8'

services:
  auth:
    build: ./back/auth
    container_name: dailybugle-auth
    ports:
      - "8081:8081"
    env_file: ./.env
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=8081 
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - bugle-net
    volumes:
      - ./back/auth/src:/usr/src/app/src

  articles:
    build: ./back/articles
    container_name: dailybugle-articles
    ports:
      - "8082:8082"
    env_file: ./.env
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=8082
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - bugle-net
    volumes:
      - ./back/articles/src:/usr/src/app/src

  ads:
    build: ./back/ads
    container_name: dailybugle-ads
    ports:
      - "8083:8083"
    env_file: ./.env
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=8083
    networks:
      - bugle-net
    volumes:
      - ./back/ads/src:/usr/src/app/src

  web-server:
    image: httpd:2.4
    container_name: dailybugle-httpd
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/local/apache2/htdocs/
    depends_on:
      - auth
      - articles
      - ads
    networks:
      - bugle-net

networks:
  bugle-net:
    driver: bridge

volumes: {}