{{- range $key, $val := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $val.name }}
  labels:
    app: {{ $val.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $val.name }}
  template:
    metadata:
      labels:
        app: {{ $val.name }}
    spec:
      containers:
        - name: {{ $val.name }}
          image: {{ $val.image }}
          imagePullPolicy: Never # Important for local 'kind' images
          ports:
            - containerPort: {{ $val.port }}
          env:
            # Set the PORT env var to match the container port
            - name: PORT
              value: "{{ $val.port }}"
            # Load secrets
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: bugle-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bugle-secrets
                  key: JWT_SECRET
{{- end }}